spring.application.name=ExampResultNotificationSystem_Mail

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sakharamchitte5@gmail.com
spring.mail.password=hjhh gfxf oeks vgcf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true