spring.application.name=MVC_NationalCricketAcademy_CRUD

#Configure dataSource

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql:///cricket_academy_db
spring.datasource.username=root
spring.datasource.password=sakharam

#JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#JSP

spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
