spring.application.name=Rest-TravelPackage-WebFlux-CRUD

# R2DBC MySQL configuration
spring.r2dbc.url=r2dbc:mysql://localhost:3306/restapi
spring.r2dbc.username=root
spring.r2dbc.password=sakharam

# Server configuration
server.port=4040